sources_dict = {
#
# Tech Sources
#
   'arstechnica': 'ARS Technica',
   'bbc': 'BBC News',
   'cnet': 'CNET',
   'computerweekly': 'Computer Weekly',
   'nytimes': 'NY Times',
   'pcmag': 'PC Mag',
   'techcrunch': 'Tech Crunch',
   'techradar': 'Tech Radar',
   'techrepublic': 'Tech Republic',
   'technologyreview': 'MIT Technology Review',
   'techtarget': 'Computer Weekly',
   'wired': 'Wired',
#
# News Sources
#
    'reuters': 'Reuters',
    'ap': 'AP',
    'foxnews': 'Fox News',
    'cnn': 'CNN',
    'wsj': 'WSJ',
    'thehill': 'The Hill',
    'nytimes': 'NY Times',
    'theguardian': 'The Guardian',
    'chicagotribune': 'Chicago Tribune',
    'aljazeera': 'Al Jazeera',
    'bbc': 'BBC',
    'bloomberg': 'Bloomberg',
    'ft':'Financial Times',
    'vox': 'Vox',
    'breitbart': 'Breitbart',
    'independent': 'The Independent',
    'washingtonpost': 'Washington Post',
    'latimes': 'LA Times',
    'washingtontimes': 'Washington Times',
    'rt': 'Russia Today',
    'dw': 'Deutsche Welle',
    'indiatimes' : 'India Times',
    'chinadaily': 'China Daily',
    'ir': 'Islamic Republic News Agency',
    'usatoday': 'USA Today', 
    'politifact': 'Politifact', 
    'allafrica': 'All Africa', 
    'pbs': 'PBS', 
    'za': 'Times Live', 
}
